CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `tbdefitems_bldgstorey` AS select `tbdefitems`.`tdi_id` AS `tdi_id`,`tbdefitems`.`tdi_td_name` AS `tdi_td_name`,`tbdefitems`.`tdi_key` AS `tdi_key`,`tbdefitems`.`tdi_value` AS `tdi_value`,`tbdefitems`.`tdi_parent_name` AS `tdi_parent_name`,`tbdefitems`.`tdi_parent_key` AS `tdi_parent_key`,`tbdefitems`.`tdi_desc` AS `tdi_desc`,`tbdefitems`.`tdi_sort` AS `tdi_sort`,`tbdefitems`.`tdi_updateby` AS `tdi_updateby`,`tbdefitems`.`tdi_updateat` AS `tdi_updateat`,`tbdefitems`.`tdi_createby` AS `tdi_createby`,`tbdefitems`.`tdicreateat` AS `tdicreateat` from `tbdefitems` where (`tbdefitems`.`tdi_td_name` = 'BUILDINGSTOREY');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `tbdefitems_bldgtype` AS select `tbdefitems`.`tdi_id` AS `tdi_id`,`tbdefitems`.`tdi_td_name` AS `tdi_td_name`,`tbdefitems`.`tdi_key` AS `tdi_key`,`tbdefitems`.`tdi_value` AS `tdi_value`,`tbdefitems`.`tdi_parent_name` AS `tdi_parent_name`,`tbdefitems`.`tdi_parent_key` AS `tdi_parent_key`,`tbdefitems`.`tdi_desc` AS `tdi_desc`,`tbdefitems`.`tdi_sort` AS `tdi_sort`,`tbdefitems`.`tdi_updateby` AS `tdi_updateby`,`tbdefitems`.`tdi_updateat` AS `tdi_updateat`,`tbdefitems`.`tdi_createby` AS `tdi_createby`,`tbdefitems`.`tdicreateat` AS `tdicreateat` from `tbdefitems` where (`tbdefitems`.`tdi_td_name` = 'BULDINGTYPE');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `tbdefitems_ishasbuilding` AS select `tbdefitems`.`tdi_id` AS `tdi_id`,`tbdefitems`.`tdi_td_name` AS `tdi_td_name`,`tbdefitems`.`tdi_key` AS `tdi_key`,`tbdefitems`.`tdi_value` AS `tdi_value`,`tbdefitems`.`tdi_parent_name` AS `tdi_parent_name`,`tbdefitems`.`tdi_parent_key` AS `tdi_parent_key`,`tbdefitems`.`tdi_desc` AS `tdi_desc`,`tbdefitems`.`tdi_sort` AS `tdi_sort`,`tbdefitems`.`tdi_updateby` AS `tdi_updateby`,`tbdefitems`.`tdi_updateat` AS `tdi_updateat`,`tbdefitems`.`tdi_createby` AS `tdi_createby`,`tbdefitems`.`tdicreateat` AS `tdicreateat` from `tbdefitems` where (`tbdefitems`.`tdi_td_name` = 'ISHASBUILDING');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `tbdefitems_subzone` AS select `tbdefitems`.`tdi_id` AS `tdi_id`,`tbdefitems`.`tdi_td_name` AS `tdi_td_name`,`tbdefitems`.`tdi_key` AS `tdi_key`,`tbdefitems`.`tdi_value` AS `tdi_value`,`tbdefitems`.`tdi_parent_name` AS `tdi_parent_name`,`tbdefitems`.`tdi_parent_key` AS `tdi_parent_key`,`tbdefitems`.`tdi_desc` AS `tdi_desc`,`tbdefitems`.`tdi_sort` AS `tdi_sort`,`tbdefitems`.`tdi_updateby` AS `tdi_updateby`,`tbdefitems`.`tdi_updateat` AS `tdi_updateat`,`tbdefitems`.`tdi_createby` AS `tdi_createby`,`tbdefitems`.`tdicreateat` AS `tdicreateat` from `tbdefitems` where (`tbdefitems`.`tdi_td_name` = 'SUBZONE');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `tbdefitems_zone` AS select `tbdefitems`.`tdi_id` AS `tdi_id`,`tbdefitems`.`tdi_td_name` AS `tdi_td_name`,`tbdefitems`.`tdi_key` AS `tdi_key`,`tbdefitems`.`tdi_value` AS `tdi_value`,`tbdefitems`.`tdi_parent_name` AS `tdi_parent_name`,`tbdefitems`.`tdi_parent_key` AS `tdi_parent_key`,`tbdefitems`.`tdi_desc` AS `tdi_desc`,`tbdefitems`.`tdi_sort` AS `tdi_sort`,`tbdefitems`.`tdi_updateby` AS `tdi_updateby`,`tbdefitems`.`tdi_updateat` AS `tdi_updateat`,`tbdefitems`.`tdi_createby` AS `tdi_createby`,`tbdefitems`.`tdicreateat` AS `tdicreateat` from `tbdefitems` where (`tbdefitems`.`tdi_td_name` = 'ZONE');
